### ISSUE TITLE
Dump jobOptions

### ISSUE THREAD

**Issue by apitka** [spflueger/bes3-boss-himster-submission#2]
Flag to dump the jobOptions for the first analysis / simulation job into a txt file.
Idea is to have jobOptions, that can be startet via "boss.exe jobOpts.txt" for debugging.

**Comment by spflueger** [comment]
Hey,
should those job options, you want to have dumped, be for a specific job within a range of jobs?
So for example you submit 50 jobs in total ranging from an index 1-50. You want to specify a job index for which the job options will be dumped so you can run boss.exe locally?
